In [21]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [32]:
def evaluate_model(name, y_test, y_pred):
    from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
    print(f"--- {name} ---")
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, zero_division=0))
    print("Recall:", recall_score(y_test, y_pred, zero_division=0))
    print("F1-Score:", f1_score(y_test, y_pred, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [22]:
data=pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Scaling dataset\Scaling_data.xlsx')

In [23]:
data.columns

Index(['Claim_Amount', 'Patient_Age', 'Patient_Gender', 'Patient_City',
       'Patient_State', 'Provider_City', 'Provider_State', 'Diagnosis_Code',
       'Procedure_Code', 'Number_of_Procedures', 'Admission_Type',
       'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount',
       'CoPay_Amount', 'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles',
       'Claim_Submitted_Late', 'Is_Fraudulent', 'Provider_Type_Hospital',
       'Provider_Type_Laboratory', 'Provider_Type_Pharmacy',
       'Provider_Type_Specialist Office', 'Provider_Type_Urgent Care',
       'Provider_Specialty_Dermatology', 'Provider_Specialty_General Practice',
       'Provider_Specialty_Neurology', 'Provider_Specialty_Oncology',
       'Provider_Specialty_Orthopedics', 'Provider_Specialty_Pediatrics',
       'Provider_Specialty_Physical Therapy', 'Provider_Specialty_Psychiatry',
       'Provider_Specialty_Radiology', 'Discharge_Type_Deceased',
       'Discharge_Type_Home', 'Discharge_Type_Rehab/Skilled Nursing',
       'Discharge_Type_Transfer to another facility', 'Claim_Year',
       'Claim_Month', 'Claim_Delay_Days'],
      dtype='object')

In [24]:
# train test split
from sklearn.model_selection import train_test_split
X = data.drop('Is_Fraudulent', axis=1)
y = data['Is_Fraudulent']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
X

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,-1.121339,-0.650370,0,-1.933469,19,-1.058893,18,-0.430195,0.399223,-1.217663,...,0,0,0,0,0,1,0,-0.796174,-0.086455,0.036400
1,0.913860,-0.194101,2,-0.733256,2,0.494558,0,2.530557,2.611934,-1.217663,...,0,0,0,1,0,0,0,1.702260,-1.550441,-1.635309
2,0.365625,1.707018,0,0.076190,4,-1.663013,12,-0.254948,-0.023204,-1.564551,...,0,0,0,1,0,0,0,0.453043,-0.379252,-0.115574
3,-0.963953,0.148100,2,-0.230841,9,-1.058893,16,-0.116595,-0.405399,-0.523887,...,0,0,0,1,0,0,0,-0.796174,1.377530,-1.521329
4,1.207168,-0.802460,0,-0.844904,4,0.926073,15,-0.420972,-0.405399,-0.176999,...,0,0,0,1,0,0,0,1.077652,-0.964847,-0.343534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20095,-0.089761,-1.372796,1,0.132014,4,-0.411622,6,2.530557,-0.194186,1.557441,...,0,0,0,0,0,1,0,1.077652,-0.964847,-1.103402
20096,-0.029113,0.566346,2,-0.537873,8,0.408256,13,0.104769,-0.526093,1.557441,...,0,0,0,0,0,0,0,1.077652,1.084733,-0.115574
20097,0.108135,-1.144661,2,0.411133,3,-0.239016,2,-0.356407,-0.948519,1.210553,...,0,0,0,0,1,0,0,-0.171565,-0.672050,-0.343534
20098,-1.089525,-0.156079,2,-0.844904,6,0.408256,10,2.512110,0.399223,-0.176999,...,0,1,0,0,0,0,1,1.077652,1.084733,-1.407349
20099,-1.545551,0.452279,0,1.750906,2,-0.411622,5,-0.725348,-0.526093,-0.176999,...,0,0,0,0,1,0,0,1.077652,0.791936,0.454327

In [26]:
y

0        0
1        1
2        0
3        1
4        0
        ..
20095    1
20096    0
20097    1
20098    0
20099    0
Name: Is_Fraudulent, Length: 20100, dtype: int64

In [27]:
# Logistic Classification
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [28]:
#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.814179104477612
Precision: 0.7168576104746317
Recall: 0.43280632411067194
F1-Score: 0.5397412199630314
Confusion Matrix:
 [[2835  173]
 [ 574  438]]

In [33]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)
y_pred = dt_pred

evaluate_model(
    "Decision Tree",
    y_test,
    dt_pred)
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

--- Decision Tree ---
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.87      0.88      3008
           1       0.63      0.65      0.64      1012

    accuracy                           0.82      4020
   macro avg       0.76      0.76      0.76      4020
weighted avg       0.82      0.82      0.82      4020

Accuracy: 0.8156716417910448
Precision: 0.6294173829990449
Recall: 0.6511857707509882
F1-Score: 0.6401165614375911
Confusion Matrix:
 [[2620  388]
 [ 353  659]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.87      0.88      3008
           1       0.63      0.65      0.64      1012

    accuracy                           0.82      4020
   macro avg       0.76      0.76      0.76      4020
weighted avg       0.82      0.82      0.82      4020

Accuracy: 0.8156716417910448
Precision: 0.6294173829990449
Recall: 0.6511857707509882
F1-Score: 0.6401165614375911
Confusion Matrix:
 [[2620  388]
 [ 353  659]]

In [34]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
y_pred = rf_pred

evaluate_model(
    "Random Forest",
    y_test,
    rf_pred
)

--- Random Forest ---
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.99      0.92      3008
           1       0.95      0.53      0.69      1012

    accuracy                           0.88      4020
   macro avg       0.91      0.76      0.80      4020
weighted avg       0.89      0.88      0.86      4020

Accuracy: 0.8763681592039801
Precision: 0.9541446208112875
Recall: 0.5345849802371542
F1-Score: 0.6852438252058265
Confusion Matrix:
 [[2982   26]
 [ 471  541]]

In [35]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.99      0.92      3008
           1       0.95      0.53      0.69      1012

    accuracy                           0.88      4020
   macro avg       0.91      0.76      0.80      4020
weighted avg       0.89      0.88      0.86      4020

Accuracy: 0.8763681592039801
Precision: 0.9541446208112875
Recall: 0.5345849802371542
F1-Score: 0.6852438252058265
Confusion Matrix:
 [[2982   26]
 [ 471  541]]

In [36]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    random_state=42
)

gb_model.fit(X_train, y_train)

gb_pred = gb_model.predict(X_test)
y_pred = gb_pred

evaluate_model(
    "Gradient Boosting",
    y_test,
    gb_pred
)

--- Gradient Boosting ---
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.98      0.92      3008
           1       0.90      0.55      0.69      1012

    accuracy                           0.87      4020
   macro avg       0.88      0.77      0.80      4020
weighted avg       0.87      0.87      0.86      4020

Accuracy: 0.8718905472636815
Precision: 0.8976
Recall: 0.5543478260869565
F1-Score: 0.6854001221747098
Confusion Matrix:
 [[2944   64]
 [ 451  561]]

In [37]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.98      0.92      3008
           1       0.90      0.55      0.69      1012

    accuracy                           0.87      4020
   macro avg       0.88      0.77      0.80      4020
weighted avg       0.87      0.87      0.86      4020

Accuracy: 0.8718905472636815
Precision: 0.8976
Recall: 0.5543478260869565
F1-Score: 0.6854001221747098
Confusion Matrix:
 [[2944   64]
 [ 451  561]]

In [38]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)
y_pred = xgb_pred

evaluate_model(
    "XGBoost",
    y_test,
    xgb_pred
)

--- XGBoost ---
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.95      0.91      3008
           1       0.81      0.61      0.70      1012

    accuracy                           0.87      4020
   macro avg       0.84      0.78      0.81      4020
weighted avg       0.86      0.87      0.86      4020

Accuracy: 0.8661691542288558
Precision: 0.8102094240837696
Recall: 0.6116600790513834
F1-Score: 0.6970720720720721
Confusion Matrix:
 [[2863  145]
 [ 393  619]]

In [39]:
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.95      0.91      3008
           1       0.81      0.61      0.70      1012

    accuracy                           0.87      4020
   macro avg       0.84      0.78      0.81      4020
weighted avg       0.86      0.87      0.86      4020

Accuracy: 0.8661691542288558
Precision: 0.8102094240837696
Recall: 0.6116600790513834
F1-Score: 0.6970720720720721
Confusion Matrix:
 [[2863  145]
 [ 393  619]]

In [40]:
from sklearn.svm import SVC

svm_model = SVC()

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

evaluate_model(
    "SVM",
    y_test,
    svm_pred
)

--- SVM ---
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.98      0.90      3008
           1       0.86      0.41      0.56      1012

    accuracy                           0.84      4020
   macro avg       0.85      0.70      0.73      4020
weighted avg       0.84      0.84      0.81      4020

Accuracy: 0.835820895522388
Precision: 0.8621399176954733
Recall: 0.4140316205533597
F1-Score: 0.5594125500667557
Confusion Matrix:
 [[2941   67]
 [ 593  419]]

In [41]:
y_pred = svm_pred
print("Classification Report:\n", classification_report(y_test, y_pred))

#accuracy,precision, recall, f1-score, confusion matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", classification_report(y_test, y_pred, output_dict=True)['1']['precision'])
print("Recall:", classification_report(y_test, y_pred, output_dict=True)['1']['recall'])
print("F1-Score:", classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'])
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.98      0.90      3008
           1       0.86      0.41      0.56      1012

    accuracy                           0.84      4020
   macro avg       0.85      0.70      0.73      4020
weighted avg       0.84      0.84      0.81      4020

Accuracy: 0.835820895522388
Precision: 0.8621399176954733
Recall: 0.4140316205533597
F1-Score: 0.5594125500667557
Confusion Matrix:
 [[2941   67]
 [ 593  419]]

In [42]:
models = {
    "Decision Tree": dt_pred,
    "Random Forest": rf_pred,
    "Gradient Boosting": gb_pred,
    "XGBoost": xgb_pred,
    "SVM": svm_pred
}

results = []

for model_name, pred in models.items():

    results.append({
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred),
        "Recall": recall_score(y_test, pred),
        "F1 Score": f1_score(y_test, pred)
    })

results_df = pd.DataFrame(results)

results_df

               Model  Accuracy  Precision    Recall  F1 Score
0      Decision Tree  0.815672   0.629417  0.651186  0.640117
1      Random Forest  0.876368   0.954145  0.534585  0.685244
2  Gradient Boosting  0.871891   0.897600  0.554348  0.685400
3            XGBoost  0.866169   0.810209  0.611660  0.697072
4                SVM  0.835821   0.862140  0.414032  0.559413

In [43]:
import os
import joblib
artifacts_dir = r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\6.Artifacts'
os.makedirs(artifacts_dir, exist_ok=True)
# Save trained models
joblib.dump(dt_model, os.path.join(artifacts_dir, 'decision_tree.pkl'))
joblib.dump(rf_model, os.path.join(artifacts_dir, 'random_forest.pkl'))
joblib.dump(gb_model, os.path.join(artifacts_dir, 'gradient_boosting.pkl'))
joblib.dump(xgb_model, os.path.join(artifacts_dir, 'xgboost.pkl'))
joblib.dump(svm_model, os.path.join(artifacts_dir, 'svm.pkl'))
joblib.dump(model, os.path.join(artifacts_dir, 'logistic_regression.pkl'))
print('Saved models to', artifacts_dir)

Saved models to D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\6.Artifacts